# the_project/ping_pong/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  selector:
    app: ping-pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000