apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: log-claim    # reuse the same PVC
      containers:
      - name: todo-app
        image: lepi23/todo_app:latest
        volumeMounts:
          - name: shared-logs
            mountPath: /shared
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
